#
###################################
# Site wide configuration
####################################
#
title: Keith Underwood
email:  keithunderwood510@gmail.com
description: A support engineer
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: keith underwood
  avatar: me.jpg
  job: "A support engineer"
  bio: "Hello Netlify, I am an engineer that enjoys helping people build and fix things."
  email: keithunderwood510@gmail.com
  disqus-shortname:
  twitter: kuwoodsays
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kuwood
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: krunderwood
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
